name: 'Dependabot check'
description: ''
inputs:
  token:
    description: ''
    required: true
  repo:
    description: 'Reference date'
    required: true
  packages:
    description: 'Repository name'
    required: true

runs:
  using: "composite"
  steps:
     - name: Checkout repo
       uses: actions/checkout@v3
     - name: Build image
       run: |
        cd .github/actions/dependabot
        docker build -t "dependabot/dependabot-script" -f Dockerfile .
      - name: Run dependabot
        env:
          PROJECT_PATH: ${{ inputs.repo }}
          DIRECTORY: /
          GITHUB_ACCESS_TOKEN: ${{ github.token }}
          PACKAGES_TO_CHECK: ${{ inputs.packages }}
        run: |
            docker run -v $PWD:/src -e PROJECT_PATH=$PROJECT_PATH -e DIRECTORY=$DIRECTORY -e PACKAGES_TO_CHECK=$PACKAGES_TO_CHECK -e GITHUB_ACCESS_TOKEN=$GITHUB_ACCESS_TOKEN -e  dependabot/dependabot-script
