name: ManualDependabot

on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'Repository name'
        default: 'ertrzyiks/graph-utils'
        required: true
      packages:
        description: 'Packages to check'
        required: true
        default: '@toptal/picasso'

jobs:
  dependabot:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Check for updates
      uses: ./.github/actions/dependabot
      with:
        token: ${{ secrets.PAT }}
        repo: ${{ inputs.repo }}
        packages: ${{ inputs.packages }}
