name: ManualDependabot

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  dependabot:
    permissions:
      contents: write  # for Git to git push
      pull-requests: write  # for repo-sync/pull-request to create pull requests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Generate the Dependency cuiser report
      uses: .github/actions/dependabot
      with:
        token: ${{ github.token }}
        repo: ertrzyiks/graph-utils
        packages: lerna
